#!/usr/bin/env sh

# echo " Ejecutando tests unitarios..."
# npm run test

# echo " Ejecutando pruebas E2E..."
# npm run cypress:run

echo " Probando build de produccion..."
npm run build

echo " Todas las verificaciones pasaron exitosamente!"
